import {quicksand} from "./font";
import "./globals.css";
import {ContextProvider} from "./globalContext/store";
import React from "react";
import ReduxProvider from "./globalRedux/provider";

export const metadata = {
    title: "AnimeMoi",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <ReduxProvider>
            <html lang="en" className={quicksand.className}>
            <body>
            <ContextProvider>{children}</ContextProvider>
            </body>
            </html>
        </ReduxProvider>
    );
}
