import './globals.css';
import {Quicksand} from 'next/font/google';
import React from "react";

export const quicksand = Quicksand({subsets: ['latin']});

export const metadata = {
    title: 'AnimeMoi',
    description: 'Generated by create next app',
};

export default function RootLayout({children}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={quicksand.className}>{children}</body>
        </html>
    );
}
